print("sdafa88".isalnum())
print("adsgfadga".isalpha())
print("344f".isdigit())
print("asfdsafaf".islower())
print("".islower())
print("DJSFHSK-j".isupper())
print("My Name is haha".istitle())
print("".istitle())
print("is hi hi ho".istitle())